import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF9F6", 
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  lista: {
    width: "100%",
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 24,
    color: "#2F5D50",
    textAlign: "center",
  },
  receitaItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginVertical: 8,
    marginHorizontal: 16,
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.06)",
    elevation: 4,
    borderWidth: 1,
    borderColor: "#E6E6E6",
  },
  thumbnail: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: 16,
    resizeMode: "cover",
    borderWidth: 2,
    borderColor: "#6B8F71",
  },
  logo: {
    width: 160,
    height: 160,
    marginBottom: 24,
    alignSelf: "center",
    resizeMode: "contain",
  },
  input: {
    width: "90%",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#A8C3A0",
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    boxShadow: "0px 3px 6px rgba(0,0,0,0.04)",
    elevation: 2,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
    color: "#D97986",
  },
  text: {
    fontSize: 16,
    marginBottom: 12,
    color: "#3C3C3C",
    lineHeight: 24,
  },
  button: {
    backgroundColor: "#6B8F71",
    paddingVertical: 16,
    borderRadius: 24,
    alignItems: "center",
    marginTop: 16,
    width: "90%",
    boxShadow: "0px 4px 8px rgba(107, 143, 113, 0.3)",
    elevation: 4,
  },
  buttonPressed: {
    backgroundColor: "#5B7F61", 
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 16,
  },
});

export default styles;
